name: Server CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      G_CLIENT_ID: ${{secrets.G_CLIENT_ID}}
      G_CLIENT_SECRET: ${{secrets.G_CLIENT_SECRET}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      working-directory: ./be/stackoverflow-be

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ env.working-directory }}

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build --build-arg G_CLIENT_ID=${{env.G_CLIENT_ID}} --build-arg G_CLIENT_SECRET=${{env.G_CLIENT_SECRET}} --build-arg JWT_SECRET_KEY=${{env.JWT_SECRET_KEY}} -t 7elenven-cicd . 
          docker tag 7elenven-cicd gdh012/7eleven-cicd:${GITHUB_SHA::7}
          docker push gdh012/7eleven-cicd:${GITHUB_SHA::7}
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: SSH Connection and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST }}  # ipv4
          username: ${{ secrets.AWS_SSH_USERNAME }} # ubuntu
          key: ${{ secrets.AWS_SSH_KEY }} #
#          port: ${{ secrets.AWS_SSH_PORT }} #
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f server
            sudo docker pull gdh012/7eleven-cicd:${GITHUB_SHA::7}
            sudo docker tag gdh012/7eleven-cicd:${GITHUB_SHA::7} 7eleven-cicd
            sudo docker run -d --name server -p 8080:8080 7eleven-cicd
